In [99]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt


In [100]:
#import the dataset
df=pd.read_csv("data.csv")

In [101]:
df.head()

stroke  horsepower  peakrpm    price
0    2.68         111     5000  13495.0
1    2.68         111     5000  16500.0
2    3.47         154     5000  16500.0
3    3.40         102     5500  13950.0
4    3.40         115     5500  17450.0

In [102]:
df.shape

(205, 4)

In [103]:
data=np.array(df)

In [104]:
x,y=data[:,0:3],data[:,3:]

In [105]:
print("the first five values are")
x[0:5]


the first five values are


array([[2.68e+00, 1.11e+02, 5.00e+03],
       [2.68e+00, 1.11e+02, 5.00e+03],
       [3.47e+00, 1.54e+02, 5.00e+03],
       [3.40e+00, 1.02e+02, 5.50e+03],
       [3.40e+00, 1.15e+02, 5.50e+03]])

In [106]:
print("the first five target variale are")
y[0:5]

the first five target variale are


array([[13495.],
       [16500.],
       [16500.],
       [13950.],
       [17450.]])

In [107]:
x.shape

(205, 3)

In [108]:
xtrain,xtest, ytrain,ytest=x[0:150],x[150:],y[0:150],y[150:]

In [109]:
print("the first five train values are")
xtrain[0:5]

the first five train values are


array([[2.68e+00, 1.11e+02, 5.00e+03],
       [2.68e+00, 1.11e+02, 5.00e+03],
       [3.47e+00, 1.54e+02, 5.00e+03],
       [3.40e+00, 1.02e+02, 5.50e+03],
       [3.40e+00, 1.15e+02, 5.50e+03]])

In [110]:
print(f"the first five train target label are:")
ytrain[0:5]

the first five train target label are:


array([[13495.],
       [16500.],
       [16500.],
       [13950.],
       [17450.]])

In [111]:
xtest[1]
print(f"the values of len of x is {len(xtrain)}")

the values of len of x is 150


In [112]:
x[0:2]

array([[2.68e+00, 1.11e+02, 5.00e+03],
       [2.68e+00, 1.11e+02, 5.00e+03]])

#defining the cost function

In [113]:
#defining the cost function to compute the cost
def compute_cost(w,b,x,y):
    Cost=0
    for k in range(len(x)):
        cost=((np.dot(w,x[k])+b)-(y[k]))**2
        Cost+=cost
    Cost=(1/(2000*len(x)))*Cost
    return Cost
    

#testing the cost function

In [114]:
wtest=np.array([1,1,1])
btest=0
print(f"the computes cosst is {compute_cost(wtest,btest,x[0:2],y[0:2])}")

the computes cosst is [49973.7020212]


#defining the gradient caluculation function

In [115]:
def compute_gradient(w,b,x,y):
    djdw=0
    djdb=0
    m=len(x)
    for k in range(m):
        dj_dw=((np.dot(w,x[k])+b)-y[k])*(x[k])
        dj_db=((np.dot(w,x[k])+b)-y[k])
    djdw=dj_dw/(2000*m)
    djdb=dj_db/(2000*m)
    return [djdw,djdb]

#testing the gradient calculating function

In [116]:
djdw,djdb=compute_gradient(wtest,btest,xtest[0:2],ytest[0:2])

In [117]:
print(f"the value of djdw is {djdw}")
print(f"the value of djdb is {djdb}")

the value of djdw is [-1.11577477e+00 -2.28310350e+01 -1.76756400e+03]
the value of djdb is [-0.3682425]


#defining the gradient descent

In [118]:
def gradient_descent(x,y,w,b,alpha,no_of_iter):
    graident_hist=[]
    costHist=[]
    w_b_Hist=[]
    for k in range(no_of_iter):
        #computing the gradient values 
        djdw,djdb=compute_gradient(w,b,x,y)
        graident_hist.append([djdw,djdb])
        #computing the cost and storing it
        cost=compute_cost(w,b,x,y)
        costHist.append(cost)
        #performing parameter updation and stroing it 
        w=w-(alpha*(djdw))
        b=b-(alpha*(djdb[0]))
    return w,b,costHist,graident_hist,w_b_Hist

In [127]:
winitial=0
binitial=0
alpha=1/(1000000)
no_of_iter_initial=50000
wfinal,bfinal,costHist,gradHist,w_b_final=gradient_descent(xtrain,ytrain,winitial,binitial,alpha,no_of_iter_initial)

In [128]:
print(f"the value of wfinal is {wfinal}")
print(f"the value of bfinal is {bfinal}")


the value of wfinal is [1.31049952e-03 5.51005478e-02 2.38272639e+00]
the value of bfinal is 0.0004964013314705223


In [129]:
xvalue=[k for k in range(len(costHist))]
for k in range(len(gradHist)):
    if k%10==0:
        print(f"the value of cost is {gradHist[k]}")

the value of cost is [array([-1.029072e-01, -4.326780e+00, -1.871040e+02]), array([-0.03898, -0.03898, -0.03898])]
the value of cost is [array([-1.02828152e-01, -4.32345640e+00, -1.86960277e+02]), array([-0.03895006])]
the value of cost is [array([-1.02749165e-01, -4.32013536e+00, -1.86816664e+02]), array([-0.03892014])]
the value of cost is [array([-1.02670239e-01, -4.31681687e+00, -1.86673162e+02]), array([-0.03889024])]
the value of cost is [array([-1.02591373e-01, -4.31350093e+00, -1.86529770e+02]), array([-0.03886037])]
the value of cost is [array([-1.02512568e-01, -4.31018753e+00, -1.86386488e+02]), array([-0.03883052])]
the value of cost is [array([-1.02433824e-01, -4.30687668e+00, -1.86243316e+02]), array([-0.03880069])]
the value of cost is [array([-1.02355140e-01, -4.30356837e+00, -1.86100254e+02]), array([-0.03877089])]
the value of cost is [array([-1.02276516e-01, -4.30026261e+00, -1.85957302e+02]), array([-0.0387411])]
the value of cost is [array([-1.02197953e-01, -4.29695

In [132]:
print("here are the prediction on first 10 data set")
for k in range(10):
    prediction=np.dot(wfinal,xtest[k])+bfinal
    print(f"the predicted value is {prediction} and the actual value is {ytest[k]}")

here are the prediction on first 10 data set
the predicted value is 11440.507378258939 and the actual value is [5348.]
the predicted value is 11440.507378258939 and the actual value is [6338.]
the predicted value is 11440.507378258939 and the actual value is [6488.]
the predicted value is 11440.507378258939 and the actual value is [6918.]
the predicted value is 11440.507378258939 and the actual value is [7898.]
the predicted value is 11440.507378258939 and the actual value is [8778.]
the predicted value is 11440.948182641285 and the actual value is [6938.]
the predicted value is 11440.948182641285 and the actual value is [7198.]
the predicted value is 10725.35927701447 and the actual value is [7898.]
the predicted value is 10725.35927701447 and the actual value is [7788.]
