In [19]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt


In [20]:
#import the dataset
df=pd.read_csv("data.csv")

In [21]:
df.head()

stroke  horsepower  peakrpm    price
0    2.68         111     5000  13495.0
1    2.68         111     5000  16500.0
2    3.47         154     5000  16500.0
3    3.40         102     5500  13950.0
4    3.40         115     5500  17450.0

In [22]:
df.shape

(205, 4)

In [23]:
data=np.array(df)

In [24]:
x,y=data[:,0:3],data[:,3:]

In [25]:
print("the first five values are")
x[0:5]


the first five values are


array([[2.68e+00, 1.11e+02, 5.00e+03],
       [2.68e+00, 1.11e+02, 5.00e+03],
       [3.47e+00, 1.54e+02, 5.00e+03],
       [3.40e+00, 1.02e+02, 5.50e+03],
       [3.40e+00, 1.15e+02, 5.50e+03]])

In [26]:
print("the first five target variale are")
y[0:5]

the first five target variale are


array([[13495.],
       [16500.],
       [16500.],
       [13950.],
       [17450.]])

In [28]:
x.shape

(205, 3)

In [33]:
xtrain,xtest, ytrain,ytest=x[0:150],x[150:],y[0:150],y[150:]

In [34]:
print("the first five train values are")
xtrain[0:5]

the first five train values are


array([[2.68e+00, 1.11e+02, 5.00e+03],
       [2.68e+00, 1.11e+02, 5.00e+03],
       [3.47e+00, 1.54e+02, 5.00e+03],
       [3.40e+00, 1.02e+02, 5.50e+03],
       [3.40e+00, 1.15e+02, 5.50e+03]])

In [36]:
print(f"the first five train target label are:")
ytrain[0:5]

the first five train target label are:


array([[13495.],
       [16500.],
       [16500.],
       [13950.],
       [17450.]])

In [38]:
xtest[1]
print(f"the values of len of x is {len(xtrain)}")

the values of len of x is 150


In [40]:
x[0:2]

array([[2.68e+00, 1.11e+02, 5.00e+03],
       [2.68e+00, 1.11e+02, 5.00e+03]])

#defining the cost function

In [59]:
#defining the cost function to compute the cost
def compute_cost(w,b,x,y):
    Cost=0
    for k in range(len(x)):
        cost=((np.dot(w,x[k])+b)-(y[k]))**2
        Cost+=cost
    Cost=(1/(2*len(x)))*Cost
    return Cost
    

#testing the cost function

In [60]:
wtest=np.array([1,1,1])
btest=0
print(f"the computes cosst is {compute_cost(wtest,btest,x[0:2],y[0:2])}")

the computes cosst is [49973702.0212]


#defining the gradient caluculation function

In [61]:
def compute_gradient(w,b,x,y):
    djdw=0
    djdb=0
    m=len(x)
    for k in range(m):
        dj_dw=((np.dot(w,x[k])+b)-y[k])*(x[k])
        dj_db=((np.dot(w,x[k])+b)-y[k])
    djdw=dj_dw/(2*m)
    djdb=dj_db/(2*m)
    return [djdw,djdb]

#testing the gradient calculating function

In [62]:
djdw,djdb=compute_gradient(wtest,btest,xtest[0:2],ytest[0:2])

In [64]:
print(f"the value of djdw is {djdw}")
print(f"the value of djdb is {djdb}")

the value of djdw is [-1.11577478e+03 -2.28310350e+04 -1.76756400e+06]
the value of djdb is [-368.2425]


#defining the gradient descent

In [66]:
def gradient_descent(x,y,w,b,alpha,no_of_iter):
    graident_hist=[]
    costHist=[]
    w_b_Hist=[]
    for k in range(no_of_iter):
        #computing the gradient values 
        djdw,djdb=compute_gradient(x,y,w,b)
        graident_hist.append([djdw,djdb])
        #computing the cost and storing it
        cost=compute_cost(x,y,w,b)
        costHist.append(cost)
        #performing parameter updation and stroing it 
        w=w-(alpha*(djdw))
        b=b-(alpha*(djdb))
    return w,b,costHist,graident_hist,w_b_Hist